export const HAMUGO_LIST = [
  {
    word: "はむはー",
    meaning: "あいさつ",
    hint: "オープニングで",
    example: "ハムスターにはなしかけるときは、「はむはー」であいさつ！",
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo01/index.html",
  },
  {
    word: "あたっちゅ",
    meaning: "たいあたり",
    hint: "オープニングで",
    example: "木にたいあたりすると、上からなにかおちてくるかもしれないよ。 ",
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo01/index.html",
  },
  {
    word: "もぐちゅ",
    meaning: "もぐる",
    hint: "オープニングで",
    example: "「やわらかいつち」の上でつかってね。なにかでてくるかも！",
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo01/index.html",
  },
  {
    word: "くんかくんか",
    meaning: "かぐ",
    hint: "オープニングで",
    example: "おちてるものをひろうとき、においをかぐときにつかってね。",
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo01/index.html",
  },
  {
    word: "イエーっちゅ",
    meaning: "はい",
    hint: "オープニングで",
    example: "元気よくへんじをしてね。",
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo01/index.html",
  },
  {
    word: "やーノン",
    meaning: "いいえ",
    hint: "オープニングで",
    example: "へんじをするときは、よくかんがえようね。",
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo01/index.html",
  },
  {
    word: "のぼちゅ",
    meaning: "のぼる",
    hint: "オープニングで",
    example: "下から見えないところにいいものがあるかも…",
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo02/index.html",
  },
  {
    word: "ガリっちょ",
    meaning: "ひっかく",
    hint: "オープニングで",
    example: "つめのお手入れをかかさずに！",
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo02/index.html",
  },
  {
    word: "キョロリン",
    meaning: "みる",
    hint: "オープニングで",
    example: "ものを探すときにつかうことばだよ",
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo02/index.html",
  },
  {
    word: "かしかし",
    meaning: "かじる",
    hint: "オープニングで",
    example: "ハム太郎ファンにはおなじみのことば",
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo02/index.html",
  },
  {
    word: "ちーぷる",
    meaning: "トイレ",
    hint: "オープニングで",
    example: "場所を選ばないと恥ずかしいよ",
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo02/index.html",
  },
  {
    word: "どっかり",
    meaning: "おおきい",
    hint: "境内",
    example: '「どんなタイプが好きかって？"どっかり"なかんじかな…」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo02/index.html",
  },
  {
    word: "ぼっち",
    meaning: "さびしい",
    hint: "森",
    example: '「"ぼっち"な家によくきたね｣',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo02/index.html",
  },
  {
    word: "がちゃちゃ",
    meaning: "うるさい",
    hint: "本殿",
    example: '「やっとねついたのに！"がちゃちゃ"しないでー！」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo02/index.html",
  },
  {
    word: "ぷりちゅ～",
    meaning: "かわいい",
    hint: "森の花",
    example: '「"ぷりちゅ～"なわたしにピッタリよ」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo02/index.html",
  },
  {
    word: "デリちゅ",
    meaning: "おいしい",
    hint: "草むら",
    example: '「このもりのどんぐりってすごく"デリちゅ"なんだ」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo02/index.html",
  },
  {
    word: "ちゃいっ",
    meaning: "ごめんなさい",
    hint: "木の上",
    example: '「だいじょうぶでちゅか…"ちゃいっ"でちゅ」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo03/index.html",
  },
  {
    word: "すかぴー",
    meaning: "ねる",
    hint: "ごろ寝",
    example: '「きもちよく"すかぴー"してるのにジャマしないで！」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo03/index.html",
  },
  {
    word: "うれぴっプル",
    meaning: "うれしい",
    hint: "赤い木の実",
    example: '「"うれぴっプル"！！」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo03/index.html",
  },
  {
    word: "ちぴっと",
    meaning: "ちいさい",
    hint: "恋の病",
    example: '「あいてはどんなこかって？"ちぴっと"なこだよ…」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo03/index.html",
  },
  {
    word: "まいちー",
    meaning: "げんきづけのことば",
    hint: "さいせんばこ",
    example: '「ケガはない？こういうこともあるさ"まいちー"！」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo03/index.html",
  },
  {
    word: "がんばリン",
    meaning: "がんばれっ",
    hint: "リボンちゃんの部屋",
    example: '「わたしのことはきにしないで"がんばリン"！」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo03/index.html",
  },
  {
    word: "サンちゅ",
    meaning: "ありがとう",
    hint: "リボンちゃん",
    example: '「それでちゅわ！"サンちゅ"でちゅわ」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo03/index.html",
  },
  {
    word: "みちゅてる",
    meaning: "ふしぎ",
    hint: "のっぽくん",
    example: '「ハム太郎くんって"みちゅてる"だな」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo03/index.html",
  },
  {
    word: "バレりっち",
    meaning: "バレる",
    hint: "公園の砂場",
    example: '「やぁ"バレりっち"？」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo03/index.html",
  },
  {
    word: "ポケらん",
    meaning: "わすれる",
    hint: "砂山",
    example: '「いくつまでかぞえたか"ポケらん"てしまったでちゅ～」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo03/index.html",
  },
  {
    word: "ひそそ",
    meaning: "ないしょ",
    hint: "花だんの看板",
    example: '「みんなには"ひそそ"だよ…」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo04/index.html",
  },
  {
    word: "うちゃー",
    meaning: "はんせい",
    hint: "砂山の穴の中",
    example: '「やっぱりすなはダメだったか…"うちゃー"」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo04/index.html",
  },
  {
    word: "ポイっちょ",
    meaning: "やめる",
    hint: "すべり台",
    example: '「もう"ポイっちょ"」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo04/index.html",
  },
  {
    word: "つっつん",
    meaning: "つっつく",
    hint: "タイショーくん",
    example: '「これを"つっつん"してください」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo04/index.html",
  },
  {
    word: "めちゅ～っ",
    meaning: "おこった",
    hint: "ジャングルジム",
    example: '「そんなことをしては"めちゅーっ"なのだ！」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo04/index.html",
  },
  {
    word: "こまっち",
    meaning: "こまる",
    hint: "こうしくん",
    example: '「そんなぁあれがないと"こまっち"ですぅ」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo04/index.html",
  },
  {
    word: "ともち",
    meaning: "ともだち",
    hint: "きゅうりのにおい",
    example: '「ペットていうか"ともち"ってカンジでちゅね」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo04/index.html",
  },
  {
    word: "ちょびりんき",
    meaning: "イケてる～",
    hint: "マフラーちゃん",
    example: '「ハム太郎くん"ちょびりんき"～」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo04/index.html",
  },
  {
    word: "ぱる",
    meaning: "ひっぱる",
    hint: "タイショーくん",
    example: '「そんなに"ぱる"しないで～」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo04/index.html",
  },
  {
    word: "でろろん",
    meaning: "つかれる",
    hint: "スタッフルーム",
    example: '「キミがやっても"でろろん"だよ」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo04/index.html",
  },
  {
    word: "わささ",
    meaning: "たくさん",
    hint: "遺跡の入口",
    example: '「ヘンテコなものが、"わささ"あるばしょだ」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo05/index.html",
  },
  {
    word: "まっちゅる",
    meaning: "ちからもち",
    hint: "遺跡",
    example: '「じぶんが有名な"まっちゅる"なはむである」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo05/index.html",
  },
  {
    word: "ぢぢぢぃ～",
    meaning: "きらい",
    hint: "遺跡",
    example: '「あなたなんか"ぢぢぢぃ～"！」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo05/index.html",
  },
  {
    word: "ぶれぶー",
    meaning: "ゆうき",
    hint: "かなあみ",
    example: '「でも、じぶんにはその"ぶれぶー"がない」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo05/index.html",
  },
  {
    word: "こそそ",
    meaning: "かくれる",
    hint: "車のかげ",
    example: '「"こそそ"してたのに見つかった」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo05/index.html",
  },
  {
    word: "おぞぞ～",
    meaning: "おそろしい",
    hint: "遺跡",
    example: '「"おぞぞ～"なばしょだ」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo05/index.html",
  },
  {
    word: "うにに～",
    meaning: "イケてな～い",
    hint: "テレビの裏",
    example: '「キミって"うにに～"」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo05/index.html",
  },
  {
    word: "てれらん",
    meaning: "はずかしい",
    hint: "ポエム",
    example: '「"てれらん"だから読まないで」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo05/index.html",
  },
  {
    word: "ぱぱらーん",
    meaning: "みせる",
    hint: "ハト時計",
    example: '「"ぱぱらーん"したらよろこんでくれたのよ」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo05/index.html",
  },
  {
    word: "じめるるん",
    meaning: "しめった",
    hint: "ピクニック",
    example: '「くうきが"じめるるん"になってきた」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo05/index.html",
  },
  {
    word: "ウ～ラ～ラ～",
    meaning: "しあわせ",
    hint: "あたっちゅボール",
    example: '「"ウ～ラ～ラ～"」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo06/index.html",
  },
  {
    word: "ばいきゅー",
    meaning: "さようなら",
    hint: "古いタイヤ",
    example: '「"ばいきゅー"」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo06/index.html",
  },
  {
    word: "うぇいきゅー",
    meaning: "まつ",
    hint: "地下ハウス",
    example: '「"うぇいきゅー"させちゃってごめんね」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo06/index.html",
  },
  {
    word: "ねがちゅる",
    meaning: "おねがい",
    hint: "ＰＣ室",
    example: '「ねぇ"ねがちゅる"ー」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo06/index.html",
  },
  {
    word: "ぴくぴ",
    meaning: "きこえる",
    hint: "トンガリくん",
    example: '「ステキな音楽が"ぴくぴ"ってこないわ…」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo06/index.html",
  },
  {
    word: "ちゅ～ラブー",
    meaning: "あいしてる",
    hint: "ＰＣ室",
    example: '「"ちゅ～ラブー"」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo06/index.html",
  },
  {
    word: "ふに～",
    meaning: "やさしい",
    hint: "校門",
    example: '「タロウちゃんはとーっても"ふに～"なワンちゃんなんでちゅ」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo06/index.html",
  },
  {
    word: "のんたる",
    meaning: "のんびり",
    hint: "お茶",
    example: '「このお茶を"のんたる"とたんのうしなさい」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo06/index.html",
  },
  {
    word: "わたた",
    meaning: "あわてる",
    hint: "パンダくん",
    example: '「穴があいているのに気づいて"わたた"したんだろぅ」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo06/index.html",
  },
  {
    word: "もっちょ",
    meaning: "アンコール",
    hint: "裏庭",
    example: '「"もっちょ"のときの歌詞でピンとくるのがないんだ」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo06/index.html",
  },
  {
    word: "がくちゅ",
    meaning: "べんきょうする",
    hint: "がいこつ",
    example: '「ボクは"がくちゅ"していただけなんでちゅ」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo07/index.html",
  },
  {
    word: "ぷっぷく",
    meaning: "もちはこぶ",
    hint: "給食室",
    example: '「"ぷっぷく"するものをてにいれなくちゃ」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo07/index.html",
  },
  {
    word: "あちゅちゅ",
    meaning: "あつい",
    hint: "タンポポ茶",
    example: '「とびきり"あちゅちゅ"なのをいれときまちた～」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo07/index.html",
  },
  {
    word: "クレレッ",
    meaning: "ちょーだい",
    hint: "トンガリくん",
    example: '「そのフレーズ"クレレッ"！だよ」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo07/index.html",
  },
  {
    word: "むちゅちゅ",
    meaning: "あそぶ",
    hint: "レジ",
    example: '「"むちゅちゅ"しとるんちゃいまっせ！？」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo07/index.html",
  },
  {
    word: "ワンダちゅ",
    meaning: "ステキ",
    hint: "新聞記者",
    example: '「これをさがしてたのよーあなたって"ワンダちゅ"」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo07/index.html",
  },
  {
    word: "もひもひ",
    meaning: "たべる",
    hint: "お菓子売り場",
    example: '「これでいっぱい"もひもひ"できるよ」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo07/index.html",
  },
  {
    word: "うりり～",
    meaning: "うる",
    hint: "自転車置き場",
    example: '「いろんなものが"うりり～"されている」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo07/index.html",
  },
  {
    word: "ペコすきー",
    meaning: "おなかすいた",
    hint: "空腹のハムスター",
    example: '「まだまだ"ペコすきー"だよ」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo07/index.html",
  },
  {
    word: "バルッち",
    meaning: "ライバル",
    hint: "冷凍倉庫",
    example: '「かれは"バルッち"だ！」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo07/index.html",
  },
  {
    word: "しーちゅる",
    meaning: "すけてる",
    hint: "飲料売場",
    example: '「ガラスは"しーちゅる"だからおもしろい」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo08/index.html",
  },
  {
    word: "プレーぜる",
    meaning: "あげる",
    hint: "倉庫",
    example: '「おれいにこれを"プレーぜる"」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo08/index.html",
  },
  {
    word: "ひえビッチ",
    meaning: "さむい",
    hint: "冷凍倉庫",
    example: '「れいとうこのなかって"ひえビッチ"」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo08/index.html",
  },
  {
    word: "ちゅきリーナ",
    meaning: "すき",
    hint: "地下ハウス",
    example: '「たしかに"ちゅきリーナ"って気持ちはいっしょ」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo08/index.html",
  },
  {
    word: "マジフル",
    meaning: "ホント",
    hint: "地下ハウス",
    example: '「"マジフル"こまりましたよー」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo08/index.html",
  },
  {
    word: "おもろぷぅ",
    meaning: "おもしろい",
    hint: "地下ハウス",
    example: '「あのふたりは"おもろぷぅ"ですよねぇ」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo08/index.html",
  },
  {
    word: "がちゅん",
    meaning: "ショック",
    hint: "ベランダ",
    example: '「えーっ"がちゅん"！」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo08/index.html",
  },
  {
    word: "フラランちゅ",
    meaning: "ふらふらする",
    hint: "トラハムちゃん",
    example: '「いつも"フラランちゅ"だから、どこにいるかわからない」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo08/index.html",
  },
  {
    word: "るんピカ",
    meaning: "おしゃれ",
    hint: "ゴルフカップ",
    example: '「リゾートでゴルフ、ぼくって"るんピカ"だよねぇ」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo08/index.html",
  },
  {
    word: "くりっくり",
    meaning: "そっくり",
    hint: "ベランダ",
    example: '「"くりっくり"な女の子をみたよ」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo08/index.html",
  },
  {
    word: "しょーなっち",
    meaning: "しかたがない",
    hint: "トラハムくん",
    example: '「"しょーなっち"、帰るとするか」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo09/index.html",
  },
  {
    word: "パーへくち",
    meaning: "かんぺき",
    hint: "コレクター",
    example: '「あと『これ』があれば"パーへくち"なんだけどなぁ」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo09/index.html",
  },
  {
    word: "あわせっち",
    meaning: "きょうりょく",
    hint: "ベランダ",
    example: '「気分いいから"あわせっち"してあげてもいいよ」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo09/index.html",
  },
  {
    word: "げんまる",
    meaning: "やくそく",
    hint: "地下ハウス",
    example: '「いくら"げんまる"してもああなのよ…」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo09/index.html",
  },
  {
    word: "クイッちゅ",
    meaning: "いそぐ",
    hint: "地下ハウス",
    example: '「じゃオレ"クイッちゅ"してるから！」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo09/index.html",
  },
  {
    word: "ゲチュー",
    meaning: "てにいれる",
    hint: "かぶるくん",
    example: '「じぶんのものはじぶんで"ゲチュー"するよ」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo09/index.html",
  },
  {
    word: "アウチッチ",
    meaning: "いたい",
    hint: "こうしくん",
    example: '「あたまが"アウチッチ"です～！！」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo09/index.html",
  },
  {
    word: "あとチョッチ",
    meaning: "おしいっ",
    hint: "パンダくん",
    example: '「工作ができないのが"あとチョッチ"なんだ」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo09/index.html",
  },
  {
    word: "べそきゅー",
    meaning: "かなしい",
    hint: "ねてるくん",
    example: '「だからねてるんじゃありませんてば～！"べそきゅー"…」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo09/index.html",
  },
  {
    word: "グレイちゅ",
    meaning: "すごーい",
    hint: "タイショーくん",
    example: '「"グレイちゅ"だなぁ！！」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo09/index.html",
  },
]
