export const HAMUGO_LIST = [
  {
    word: "はむはー",
    meaning: "いみ：「あいさつ」",
    hint: "オープニングで",
    example: "ハムスターにはなしかけるときは、「はむはー」であいさつ！",
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo01/index.html",
  },
  {
    word: "あたっちゅ",
    meaning: "いみ：「たいあたり」",
    hint: "オープニングで",
    example: "木にたいあたりすると、上からなにかおちてくるかもしれないよ。 ",
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo01/index.html",
  },
  {
    word: "もぐちゅ",
    meaning: "いみ：「もぐる」",
    hint: "オープニングで",
    example: "「やわらかいつち」の上でつかってね。なにかでてくるかも！",
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo01/index.html",
  },
  {
    word: "くんかくんか",
    meaning: "いみ：「かぐ」",
    hint: "オープニングで",
    example: "おちてるものをひろうとき、においをかぐときにつかってね。",
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo01/index.html",
  },
  {
    word: "イエーっちゅ",
    meaning: "いみ「はい」",
    hint: "オープニングで",
    example: "元気よくへんじをしてね。",
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo01/index.html",
  },
  {
    word: "やーノン",
    meaning: "いみ「いいえ」",
    hint: "オープニングで",
    example: "へんじをするときは、よくかんがえようね。",
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo01/index.html",
  },
  {
    word: "のぼちゅ",
    meaning: "いみ「のぼる」",
    hint: "オープニングで",
    example: "下から見えないところにいいものがあるかも…",
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo02/index.html",
  },
  {
    word: "ガリっちょ",
    meaning: "いみ「ひっかく」",
    hint: "オープニングで",
    example: "つめのお手入れをかかさずに！",
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo02/index.html",
  },
  {
    word: "キョロリン",
    meaning: "いみ「みる」",
    hint: "オープニングで",
    example: "ものを探すときにつかうことばだよ",
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo02/index.html",
  },
  {
    word: "かしかし",
    meaning: "いみ「かじる」",
    hint: "オープニングで",
    example: "ハム太郎ファンにはおなじみのことば",
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo02/index.html",
  },
  {
    word: "ちーぷる",
    meaning: "いみ「トイレ」",
    hint: "オープニングで",
    example: "場所を選ばないと恥ずかしいよ",
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo02/index.html",
  },
  {
    word: "どっかり",
    meaning: "いみ「おおきい」",
    hint: "境内",
    example: '「どんなタイプが好きかって？"どっかり"なかんじかな…」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo02/index.html",
  },
  {
    word: "ぼっち",
    meaning: "いみ「さびしい」",
    hint: "森",
    example: '「"ぼっち"な家によくきたね｣',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo02/index.html",
  },
  {
    word: "がちゃちゃ",
    meaning: "いみ「うるさい」",
    hint: "本殿",
    example: '「やっとねついたのに！"がちゃちゃ"しないでー！」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo02/index.html",
  },
  {
    word: "ぷりちゅ～",
    meaning: "いみ「かわいい」",
    hint: "森の花",
    example: '「"ぷりちゅ～"なわたしにピッタリよ」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo02/index.html",
  },
  {
    word: "デリちゅ",
    meaning: "いみ「おいしい」",
    hint: "草むら",
    example: '「このもりのどんぐりってすごく"デリちゅ"なんだ」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo02/index.html",
  },
  {
    word: "ちゃいっ",
    meaning: "いみ「ごめんなさい」",
    hint: "木の上",
    example: '「だいじょうぶでちゅか…"ちゃいっ"でちゅ」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo03/index.html",
  },
  {
    word: "すかぴー",
    meaning: "いみ「ねる」",
    hint: "ごろ寝",
    example: '「きもちよく"すかぴー"してるのにジャマしないで！」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo03/index.html",
  },
  {
    word: "うれぴっプル",
    meaning: "いみ「うれしい」",
    hint: "赤い木の実",
    example: '「"うれぴっプル"！！」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo03/index.html",
  },
  {
    word: "ちぴっと",
    meaning: "いみ「ちいさい」",
    hint: "恋の病",
    example: '「あいてはどんなこかって？"ちぴっと"なこだよ…」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo03/index.html",
  },
  {
    word: "まいちー",
    meaning: "いみ「げんきづけのことば」",
    hint: "さいせんばこ",
    example: '「ケガはない？こういうこともあるさ"まいちー"！」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo03/index.html",
  },
  {
    word: "がんばリン",
    meaning: "いみ「がんばれっ」",
    hint: "リボンちゃんの部屋",
    example: '「わたしのことはきにしないで"がんばリン"！」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo03/index.html",
  },
  {
    word: "サンちゅ",
    meaning: "いみ「ありがとう」",
    hint: "リボンちゃん",
    example: '「それでちゅわ！"サンちゅ"でちゅわ」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo03/index.html",
  },
  {
    word: "みちゅてる",
    meaning: "いみ「ふしぎ」",
    hint: "のっぽくん",
    example: '「ハム太郎くんって"みちゅてる"だな」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo03/index.html",
  },
  {
    word: "バレりっち",
    meaning: "いみ「バレる」",
    hint: "公園の砂場",
    example: '「やぁ"バレりっち"？」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo03/index.html",
  },
  {
    word: "ポケらん",
    meaning: "いみ「わすれる」",
    hint: "砂山",
    example: '「いくつまでかぞえたか"ポケらん"てしまったでちゅ～」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo03/index.html",
  },
  {
    word: "ひそそ",
    meaning: "いみ「ないしょ」",
    hint: "花だんの看板",
    example: '「みんなには"ひそそ"だよ…」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo04/index.html",
  },
  {
    word: "うちゃー",
    meaning: "いみ「はんせい」",
    hint: "砂山の穴の中",
    example: '「やっぱりすなはダメだったか…"うちゃー"」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo04/index.html",
  },
  {
    word: "ポイっちょ",
    meaning: "いみ「やめる」",
    hint: "すべり台",
    example: '「もう"ポイっちょ"」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo04/index.html",
  },
  {
    word: "つっつん",
    meaning: "いみ「つっつく」",
    hint: "タイショーくん",
    example: '「これを"つっつん"してください」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo04/index.html",
  },
  {
    word: "めちゅ～っ",
    meaning: "いみ「おこった」",
    hint: "ジャングルジム",
    example: '「そんなことをしては"めちゅーっ"なのだ！」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo04/index.html",
  },
  {
    word: "こまっち",
    meaning: "いみ「こまる」",
    hint: "こうしくん",
    example: '「そんなぁあれがないと"こまっち"ですぅ」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo04/index.html",
  },
  {
    word: "ともち",
    meaning: "いみ「ともだち」",
    hint: "きゅうりのにおい",
    example: '「ペットていうか"ともち"ってカンジでちゅね」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo04/index.html",
  },
  {
    word: "ちょびりんき",
    meaning: "いみ「イケてる～」",
    hint: "マフラーちゃん",
    example: '「ハム太郎くん"ちょびりんき"～」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo04/index.html",
  },
  {
    word: "ぱる",
    meaning: "いみ「ひっぱる」",
    hint: "タイショーくん",
    example: '「そんなに"ぱる"しないで～」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo04/index.html",
  },
  {
    word: "でろろん",
    meaning: "いみ「つかれる」",
    hint: "スタッフルーム",
    example: '「キミがやっても"でろろん"だよ」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo04/index.html",
  },
  {
    word: "わささ",
    meaning: "いみ「たくさん」",
    hint: "遺跡の入口",
    example: '「ヘンテコなものが、"わささ"あるばしょだ」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo05/index.html",
  },
  {
    word: "まっちゅる",
    meaning: "いみ「ちからもち」",
    hint: "遺跡",
    example: '「じぶんが有名な"まっちゅる"なはむである」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo05/index.html",
  },
  {
    word: "ぢぢぢぃ～",
    meaning: "いみ「きらい」",
    hint: "遺跡",
    example: '「あなたなんか"ぢぢぢぃ～"！」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo05/index.html",
  },
  {
    word: "ぶれぶー",
    meaning: "いみ「ゆうき」",
    hint: "かなあみ",
    example: '「でも、じぶんにはその"ぶれぶー"がない」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo05/index.html",
  },
  {
    word: "こそそ",
    meaning: "いみ「かくれる」",
    hint: "車のかげ",
    example: '「"こそそ"してたのに見つかった」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo05/index.html",
  },
  {
    word: "おぞぞ～",
    meaning: "いみ「おそろしい」",
    hint: "遺跡",
    example: '「"おぞぞ～"なばしょだ」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo05/index.html",
  },
  {
    word: "うにに～",
    meaning: "いみ「イケてな～い」",
    hint: "テレビの裏",
    example: '「キミって"うにに～"」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo05/index.html",
  },
  {
    word: "てれらん",
    meaning: "いみ「はずかしい」",
    hint: "ポエム",
    example: '「"てれらん"だから読まないで」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo05/index.html",
  },
  {
    word: "ぱぱらーん",
    meaning: "いみ「みせる」",
    hint: "ハト時計",
    example: '「"ぱぱらーん"したらよろこんでくれたのよ」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo05/index.html",
  },
  {
    word: "じめるるん",
    meaning: "いみ「しめった」",
    hint: "ピクニック",
    example: '「くうきが"じめるるん"になってきた」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo05/index.html",
  },
  {
    word: "ウ～ラ～ラ～",
    meaning: "いみ「しあわせ」",
    hint: "あたっちゅボール",
    example: '「"ウ～ラ～ラ～"」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo06/index.html",
  },
  {
    word: "ばいきゅー",
    meaning: "いみ「さようなら」",
    hint: "古いタイヤ",
    example: '「"ばいきゅー"」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo06/index.html",
  },
  {
    word: "うぇいきゅー",
    meaning: "いみ「まつ」",
    hint: "地下ハウス",
    example: '「"うぇいきゅー"させちゃってごめんね」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo06/index.html",
  },
  {
    word: "ねがちゅる",
    meaning: "いみ「おねがい」",
    hint: "ＰＣ室",
    example: '「ねぇ"ねがちゅる"ー」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo06/index.html",
  },
  {
    word: "ぴくぴ",
    meaning: "いみ「きこえる」",
    hint: "トンガリくん",
    example: '「ステキな音楽が"ぴくぴ"ってこないわ…」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo06/index.html",
  },
  {
    word: "ちゅ～ラブー",
    meaning: "いみ「あいしてる」",
    hint: "ＰＣ室",
    example: '「"ちゅ～ラブー"」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo06/index.html",
  },
  {
    word: "ふに～",
    meaning: "いみ「やさしい」",
    hint: "校門",
    example: '「タロウちゃんはとーっても"ふに～"なワンちゃんなんでちゅ」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo06/index.html",
  },
  {
    word: "のんたる",
    meaning: "いみ「のんびり」",
    hint: "お茶",
    example: '「このお茶を"のんたる"とたんのうしなさい」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo06/index.html",
  },
  {
    word: "わたた",
    meaning: "いみ「あわてる」",
    hint: "パンダくん",
    example: '「穴があいているのに気づいて"わたた"したんだろぅ」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo06/index.html",
  },
  {
    word: "もっちょ",
    meaning: "いみ「アンコール」",
    hint: "裏庭",
    example: '「"もっちょ"のときの歌詞でピンとくるのがないんだ」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo06/index.html",
  },
  {
    word: "がくちゅ",
    meaning: "いみ「べんきょうする」",
    hint: "がいこつ",
    example: '「ボクは"がくちゅ"していただけなんでちゅ」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo07/index.html",
  },
  {
    word: "ぷっぷく",
    meaning: "いみ「もちはこぶ」",
    hint: "給食室",
    example: '「"ぷっぷく"するものをてにいれなくちゃ」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo07/index.html",
  },
  {
    word: "あちゅちゅ",
    meaning: "いみ「あつい」",
    hint: "タンポポ茶",
    example: '「とびきり"あちゅちゅ"なのをいれときまちた～」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo07/index.html",
  },
  {
    word: "クレレッ",
    meaning: "いみ「ちょーだい」",
    hint: "トンガリくん",
    example: '「そのフレーズ"クレレッ"！だよ」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo07/index.html",
  },
  {
    word: "むちゅちゅ",
    meaning: "いみ「あそぶ」",
    hint: "レジ",
    example: '「"むちゅちゅ"しとるんちゃいまっせ！？」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo07/index.html",
  },
  {
    word: "ワンダちゅ",
    meaning: "いみ「ステキ」",
    hint: "新聞記者",
    example: '「これをさがしてたのよーあなたって"ワンダちゅ"」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo07/index.html",
  },
  {
    word: "もひもひ",
    meaning: "いみ「たべる」",
    hint: "お菓子売り場",
    example: '「これでいっぱい"もひもひ"できるよ」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo07/index.html",
  },
  {
    word: "うりり～",
    meaning: "いみ「うる」",
    hint: "自転車置き場",
    example: '「いろんなものが"うりり～"されている」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo07/index.html",
  },
  {
    word: "ペコすきー",
    meaning: "いみ「おなかすいた」",
    hint: "空腹のハムスター",
    example: '「まだまだ"ペコすきー"だよ」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo07/index.html",
  },
  {
    word: "バルッち",
    meaning: "いみ「ライバル」",
    hint: "冷凍倉庫",
    example: '「かれは"バルッち"だ！」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo07/index.html",
  },
  {
    word: "しーちゅる",
    meaning: "いみ「すけてる」",
    hint: "飲料売場",
    example: '「ガラスは"しーちゅる"だからおもしろい」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo08/index.html",
  },
  {
    word: "プレーぜる",
    meaning: "いみ「あげる」",
    hint: "倉庫",
    example: '「おれいにこれを"プレーぜる"」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo08/index.html",
  },
  {
    word: "ひえビッチ",
    meaning: "いみ「さむい」",
    hint: "冷凍倉庫",
    example: '「れいとうこのなかって"ひえビッチ"」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo08/index.html",
  },
  {
    word: "ちゅきリーナ",
    meaning: "いみ「すき」",
    hint: "地下ハウス",
    example: '「たしかに"ちゅきリーナ"って気持ちはいっしょ」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo08/index.html",
  },
  {
    word: "マジフル",
    meaning: "いみ「ホント」",
    hint: "地下ハウス",
    example: '「"マジフル"こまりましたよー」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo08/index.html",
  },
  {
    word: "おもろぷぅ",
    meaning: "いみ「おもしろい」",
    hint: "地下ハウス",
    example: '「あのふたりは"おもろぷぅ"ですよねぇ」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo08/index.html",
  },
  {
    word: "がちゅん",
    meaning: "いみ「ショック」",
    hint: "ベランダ",
    example: '「えーっ"がちゅん"！」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo08/index.html",
  },
  {
    word: "フラランちゅ",
    meaning: "いみ「ふらふらする」",
    hint: "トラハムちゃん",
    example: '「いつも"フラランちゅ"だから、どこにいるかわからない」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo08/index.html",
  },
  {
    word: "るんピカ",
    meaning: "いみ「おしゃれ」",
    hint: "ゴルフカップ",
    example: '「リゾートでゴルフ、ぼくって"るんピカ"だよねぇ」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo08/index.html",
  },
  {
    word: "くりっくり",
    meaning: "いみ「そっくり」",
    hint: "ベランダ",
    example: '「"くりっくり"な女の子をみたよ」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo08/index.html",
  },
  {
    word: "しょーなっち",
    meaning: "いみ「しかたがない」",
    hint: "トラハムくん",
    example: '「"しょーなっち"、帰るとするか」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo09/index.html",
  },
  {
    word: "パーへくち",
    meaning: "いみ「かんぺき」",
    hint: "コレクター",
    example: '「あと『これ』があれば"パーへくち"なんだけどなぁ」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo09/index.html",
  },
  {
    word: "あわせっち",
    meaning: "いみ「きょうりょく」",
    hint: "ベランダ",
    example: '「気分いいから"あわせっち"してあげてもいいよ」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo09/index.html",
  },
  {
    word: "げんまる",
    meaning: "いみ「やくそく」",
    hint: "地下ハウス",
    example: '「いくら"げんまる"してもああなのよ…」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo09/index.html",
  },
  {
    word: "クイッちゅ",
    meaning: "いみ「いそぐ」",
    hint: "地下ハウス",
    example: '「じゃオレ"クイッちゅ"してるから！」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo09/index.html",
  },
  {
    word: "ゲチュー",
    meaning: "いみ「てにいれる」",
    hint: "かぶるくん",
    example: '「じぶんのものはじぶんで"ゲチュー"するよ」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo09/index.html",
  },
  {
    word: "アウチッチ",
    meaning: "いみ「いたい」",
    hint: "こうしくん",
    example: '「あたまが"アウチッチ"です～！！」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo09/index.html",
  },
  {
    word: "あとチョッチ",
    meaning: "いみ「おしいっ」",
    hint: "パンダくん",
    example: '「工作ができないのが"あとチョッチ"なんだ」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo09/index.html",
  },
  {
    word: "べそきゅー",
    meaning: "いみ「かなしい」",
    hint: "ねてるくん",
    example: '「だからねてるんじゃありませんてば～！"べそきゅー"…」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo09/index.html",
  },
  {
    word: "グレイちゅ",
    meaning: "いみ「すごーい」",
    hint: "タイショーくん",
    example: '「"グレイちゅ"だなぁ！！」',
    url: "https://www.nintendo.co.jp/n02/dmg/b86j/hamugo09/index.html",
  },
]
